'use client';

import { useState, useEffect } from 'react';
import { Session } from '@/lib/generator';
import { useI18n } from '@/lib/i18n';
import { isWorkoutDone, markWorkoutDone } from '@/lib/storage';
import type { ExerciseLogEntry } from '@/lib/storage';
import ExerciseLogPanel from './ExerciseLogPanel';

const YTIcon = () => (
  <svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="currentColor">
    <path d="M23.498 6.186a3.016 3.016 0 0 0-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.377.505A3.017 3.017 0 0 0 .502 6.186C0 8.07 0 12 0 12s0 3.93.502 5.814a3.016 3.016 0 0 0 2.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.015 3.015 0 0 0 2.122-2.136C24 15.93 24 12 24 12s0-3.93-.502-5.814zM9.545 15.568V8.432L15.818 12l-6.273 3.568z" />
  </svg>
);

function DemoLink({ search, label }: { search: string; label: string }) {
  return (
    <a
      href={`https://www.youtube.com/results?search_query=${encodeURIComponent(search)}`}
      target="_blank"
      rel="noopener noreferrer"
      className="inline-flex items-center gap-1.5 mt-1.5 px-2.5 py-1 rounded bg-zinc-800 text-zinc-400 text-xs hover:text-zinc-200 transition-colors"
    >
      <YTIcon />
      {label}
    </a>
  );
}

function formatLogDate(dateStr: string, lang: string): string {
  const d = new Date(dateStr + 'T00:00:00');
  if (lang === 'es') {
    const months = ['ene', 'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct', 'nov', 'dic'];
    return `${d.getDate()} ${months[d.getMonth()]}`;
  }
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  return `${months[d.getMonth()]} ${d.getDate()}`;
}

function buildChatGPTPrompt(session: Session, lang: string): string {
  const lines: string[] = [];

  // System context for the LLM
  if (lang === 'es') {
    lines.push('Eres un entrenador personal experto. Te paso un entrenamiento generado por Hormesis (hormesis-pt.vercel.app). Tu trabajo es adaptarlo a MI situacion especifica.');
    lines.push('');
    lines.push(`ENTRENAMIENTO DE HOY:`);
    lines.push(`Fecha: ${session.date} (${session.dayName_es}) | Tipo: ${session.sessionType_es} | ~${session.duration} min`);
    lines.push(`Mesociclo: ${session.phase.label_es} — ${session.phase.description_es}`);
  } else {
    lines.push('You are an expert personal trainer. I\'m sharing a workout generated by Hormesis (hormesis-pt.vercel.app). Your job is to adapt it to MY specific situation.');
    lines.push('');
    lines.push(`TODAY'S WORKOUT:`);
    lines.push(`Date: ${session.date} (${session.dayName}) | Type: ${session.sessionType} | ~${session.duration} min`);
    lines.push(`Mesocycle: ${session.phase.label} — ${session.phase.description}`);
  }
  lines.push('');

  // Warmup
  if (session.warmup.exercises.length > 0) {
    const wf = lang === 'es' ? session.warmup.format.name_es : session.warmup.format.name;
    lines.push(lang === 'es' ? `CALENTAMIENTO (${wf}):` : `WARM-UP (${wf}):`);
    for (const w of session.warmup.exercises) {
      lines.push(`  ${w.exercise.name} — ${w.exercise.prescription}`);
    }
    lines.push('');
  }

  // Strength
  if (session.strength.length > 0) {
    lines.push(lang === 'es' ? 'FUERZA:' : 'STRENGTH:');
    for (const s of session.strength) {
      const tempoStr = s.tempo ? ` | Tempo ${s.tempo}` : '';
      const proto = lang === 'es' ? s.protocol_es : s.protocol;
      lines.push(`  ${s.exercise.name} [${proto}]: ${s.sets}x${s.reps} @ ${s.load} | Rest ${s.rest}${tempoStr}`);
    }
    lines.push('');
  }

  // WOD
  lines.push('WOD:');
  lines.push(`  ${lang === 'es' ? session.conditioning.formatName_es : session.conditioning.formatName} | Cap: ${session.conditioning.timecap}`);
  for (const m of session.conditioning.movements) {
    const loadStr = m.load !== 'BW' ? ` (${m.load})` : '';
    lines.push(`  ${m.reps} ${m.name}${loadStr}`);
  }
  lines.push('');

  // Precise adaptation prompt
  if (lang === 'es') {
    lines.push('---');
    lines.push('MI SITUACION (rellena lo que aplique):');
    lines.push('');
    lines.push('EQUIPAMIENTO:');
    lines.push('- Mancuernas: ___kg (ligeras) y ___kg (pesadas)');
    lines.push('- Barra de dominadas: si / no');
    lines.push('- Comba: si / no');
    lines.push('- Otro: ___');
    lines.push('');
    lines.push('CUERPO:');
    lines.push('- Dolor o lesiones activas: [zona del cuerpo + tipo: agudo/cronico/molestia]');
    lines.push('- Zonas rigidas o con poca movilidad: [ej: caderas, hombros, tobillo]');
    lines.push('- Problemas de suelo pelvico: si / no');
    lines.push('');
    lines.push('NIVEL Y OBJETIVO:');
    lines.push('- Experiencia: [principiante / intermedio / avanzado]');
    lines.push('- Objetivo principal: [fuerza / hipertrofia / resistencia / perdida de grasa / salud general]');
    lines.push('- Tiempo disponible hoy: [__ minutos]');
    lines.push('');
    lines.push('INSTRUCCIONES:');
    lines.push('1. Mantiene la estructura: Calentamiento → Fuerza → WOD');
    lines.push('2. Sustituye SOLO los ejercicios que no pueda hacer por mi equipamiento o lesiones');
    lines.push('3. Si sustituyes, explica POR QUE ese ejercicio alternativo trabaja el mismo patron');
    lines.push('4. Ajusta las reps/sets/carga segun mi nivel');
    lines.push('5. Si tengo dolor en alguna zona, evita ESA zona y dame alternativas seguras');
    lines.push('6. Dame el entreno final completo y listo para ejecutar');
  } else {
    lines.push('---');
    lines.push('MY SITUATION (fill in what applies):');
    lines.push('');
    lines.push('EQUIPMENT:');
    lines.push('- Dumbbells: ___kg (light) and ___kg (heavy)');
    lines.push('- Pull-up bar: yes / no');
    lines.push('- Jump rope: yes / no');
    lines.push('- Other: ___');
    lines.push('');
    lines.push('BODY:');
    lines.push('- Active pain or injuries: [body area + type: acute/chronic/discomfort]');
    lines.push('- Stiff or limited mobility areas: [e.g. hips, shoulders, ankle]');
    lines.push('- Pelvic floor issues: yes / no');
    lines.push('');
    lines.push('LEVEL & GOAL:');
    lines.push('- Experience: [beginner / intermediate / advanced]');
    lines.push('- Main goal: [strength / hypertrophy / endurance / fat loss / general health]');
    lines.push('- Time available today: [__ minutes]');
    lines.push('');
    lines.push('INSTRUCTIONS:');
    lines.push('1. Keep the structure: Warm-up → Strength → WOD');
    lines.push('2. ONLY substitute exercises I can\'t do because of my equipment or injuries');
    lines.push('3. If you substitute, explain WHY that alternative works the same movement pattern');
    lines.push('4. Adjust reps/sets/load for my level');
    lines.push('5. If I have pain in any area, avoid THAT area and give safe alternatives');
    lines.push('6. Give me the final workout complete and ready to execute');
  }

  return lines.join('\n');
}

export default function WorkoutDisplay({ session, onSwapStrength, lastLogs = {}, readOnly = false, onDone }: { session: Session; onSwapStrength?: (index: number) => void; lastLogs?: Record<string, ExerciseLogEntry | null>; readOnly?: boolean; onDone?: () => void }) {
  const { t, lang } = useI18n();
  const [copied, setCopied] = useState(false);
  const [done, setDone] = useState(false);
  const [showLog, setShowLog] = useState(false);

  useEffect(() => {
    setDone(isWorkoutDone(session.date));
    setShowLog(false);
  }, [session.date]);

  async function handleCopy() {
    const prompt = buildChatGPTPrompt(session, lang);
    try {
      await navigator.clipboard.writeText(prompt);
    } catch {
      const textarea = document.createElement('textarea');
      textarea.value = prompt;
      textarea.style.position = 'fixed';
      textarea.style.opacity = '0';
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
    }
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <div className="font-mono text-sm leading-relaxed space-y-6">
      {/* Phase banner */}
      <a href="/program" className="block text-center px-4 py-2.5 rounded-lg bg-fuchsia-500/10 border border-fuchsia-500/20 hover:bg-fuchsia-500/15 transition-colors">
        <p className="text-fuchsia-400 text-xs font-bold uppercase tracking-wider">
          {lang === 'es' ? session.phase.label_es : session.phase.label}
          <span className="text-fuchsia-400/50 font-normal ml-1.5">
            {lang === 'es' ? `dia ${session.phase.dayInWeek}/7` : `day ${session.phase.dayInWeek}/7`}
          </span>
        </p>
        <p className="text-fuchsia-400/60 text-xs mt-0.5">
          {lang === 'es' ? session.phase.description_es : session.phase.description}
          <span className="ml-1 text-fuchsia-400/40">→</span>
        </p>
      </a>

      {/* Header */}
      <div className="text-center space-y-1">
        <h2 className="text-2xl font-bold text-foreground">
          {lang === 'es' ? session.sessionType_es : session.sessionType}
        </h2>
        <p className="text-muted text-xs">
          {lang === 'es' ? session.dayName_es : session.dayName} — {session.date} — ~{session.duration} min
        </p>
      </div>

      {/* Warm-up — GREEN */}
      {session.warmup.exercises.length > 0 && (
        <div className="border-2 border-emerald-500/40 rounded-lg p-4 bg-emerald-500/5">
          <h3 className="text-emerald-400 font-bold mb-1 text-xs uppercase tracking-wider">
            {t('Warm-up', 'Calentamiento')}
          </h3>
          <p className="text-emerald-400 font-bold text-sm mb-1">
            {lang === 'es' ? session.warmup.format.name_es : session.warmup.format.name}
          </p>
          <p className="text-emerald-400/60 text-xs mb-3">
            {lang === 'es' ? session.warmup.format.detail_es : session.warmup.format.detail}
          </p>
          <ul className="space-y-2">
            {session.warmup.exercises.map((w, i) => (
              <li key={i} className="pl-4 border-l-2 border-emerald-500/30">
                <span className="text-foreground">{w.exercise.name}</span>
                <span className="text-muted"> — {w.exercise.prescription}</span>
                <p className="text-muted text-xs mt-0.5">
                  {lang === 'es' ? w.exercise.cue_es : w.exercise.cue}
                </p>
                {w.exercise.demoSearch && (
                  <DemoLink search={w.exercise.demoSearch} label={t('Demo', 'Demo')} />
                )}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Strength — RED */}
      {session.strength.length > 0 && (
        <div className="border-2 border-red-500/40 rounded-lg p-4 bg-red-500/5">
          <h3 className="text-red-400 font-bold mb-3 text-xs uppercase tracking-wider">
            {t('Strength', 'Fuerza')}
          </h3>
          <div className="space-y-4">
            {session.strength.map((item, i) => (
              <div key={i} className="pl-4 border-l-2 border-red-500/30">
                <div className="flex flex-wrap items-baseline gap-2">
                  <span className="text-foreground font-medium">{item.exercise.name}</span>
                  {onSwapStrength && (
                    <button
                      onClick={() => onSwapStrength(i)}
                      className="ml-1 px-2 py-1 text-xs text-red-400/60 hover:text-red-400 hover:bg-red-500/10 rounded transition-colors cursor-pointer inline-flex items-center gap-1"
                      aria-label={t('Swap exercise', 'Cambiar ejercicio')}
                    >
                      <svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <path d="M1 4v6h6" />
                        <path d="M23 20v-6h-6" />
                        <path d="M20.49 9A9 9 0 0 0 5.64 5.64L1 10M23 14l-4.64 4.36A9 9 0 0 1 3.51 15" />
                      </svg>
                      {t('swap', 'cambiar')}
                    </button>
                  )}
                  <span className="text-xs px-1.5 py-0.5 rounded bg-red-500/15 text-red-400 border border-red-500/20">
                    {lang === 'es' ? item.protocol_es : item.protocol}
                  </span>
                </div>
                <p className="text-red-400 text-xs mt-1">
                  {item.sets}x{item.reps} @ {item.load} | {t('Rest', 'Descanso')}: {item.rest}
                  {item.tempo && ` | Tempo: ${item.tempo}`}
                </p>
                <p className="text-muted text-xs mt-1">
                  {lang === 'es' ? item.protocolNote_es : item.protocolNote}
                </p>
                <p className="text-muted text-xs">
                  {lang === 'es' ? item.exercise.cue_es : item.exercise.cue}
                </p>
                <DemoLink search={item.exercise.demoSearch} label={t('Demo', 'Demo')} />
                {lastLogs[item.exercise.id] && lastLogs[item.exercise.id]!.weight && (
                  <p className="text-zinc-500 text-xs mt-1.5">
                    {t('Last', 'Anterior')}: {lastLogs[item.exercise.id]!.weight} x {lastLogs[item.exercise.id]!.reps}
                    {' '}({formatLogDate(lastLogs[item.exercise.id]!.date, lang)})
                  </p>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* WOD — ORANGE */}
      <div className="border-2 border-orange-500/40 rounded-lg p-4 bg-orange-500/5">
        <h3 className="text-orange-400 font-bold mb-1 text-xs uppercase tracking-wider">
          WOD
        </h3>

        <p className="text-foreground font-bold text-sm mb-1">
          {lang === 'es' ? session.conditioning.formatName_es : session.conditioning.formatName}
          <span className="text-orange-400 ml-2">
            | Cap: {session.conditioning.timecap}
          </span>
        </p>

        {/* Format description */}
        <p className="text-orange-400/60 text-xs mb-2">
          {lang === 'es' ? session.conditioning.formatDescription_es : session.conditioning.formatDescription}
        </p>

        {/* Intensity + Volume tags */}
        <div className="flex flex-wrap gap-2 mb-3">
          <span className="text-xs px-2 py-0.5 rounded bg-orange-500/15 text-orange-400 border border-orange-500/20">
            {lang === 'es' ? session.conditioning.intensity_es : session.conditioning.intensity}
          </span>
          <span className="text-xs px-2 py-0.5 rounded bg-orange-500/10 text-orange-400/80 border border-orange-500/15">
            {lang === 'es' ? session.conditioning.volume_es : session.conditioning.volume}
          </span>
        </div>

        <div className="space-y-2 mb-3">
          {session.conditioning.movements.map((m, i) => (
            <div key={i} className="text-sm">
              <span className="font-mono font-bold text-orange-400">
                {m.reps}
              </span>
              <span className="text-foreground ml-2">{m.name}</span>
              {m.load !== 'BW' && (
                <span className="text-muted ml-1">({m.load})</span>
              )}
              <a
                href={`https://www.youtube.com/results?search_query=${encodeURIComponent(m.demoSearch)}`}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-1 ml-2 text-xs text-orange-400/60 hover:text-orange-400 transition-colors"
              >
                <svg className="w-3 h-3" viewBox="0 0 24 24" fill="currentColor">
                  <path d="M23.498 6.186a3.016 3.016 0 0 0-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.377.505A3.017 3.017 0 0 0 .502 6.186C0 8.07 0 12 0 12s0 3.93.502 5.814a3.016 3.016 0 0 0 2.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.015 3.015 0 0 0 2.122-2.136C24 15.93 24 12 24 12s0-3.93-.502-5.814zM9.545 15.568V8.432L15.818 12l-6.273 3.568z" />
                </svg>
                demo
              </a>
            </div>
          ))}
        </div>

        <p className="text-muted text-xs italic">
          {lang === 'es' ? session.conditioning.note_es : session.conditioning.note}
        </p>

        {session.conditioning.scalingNote && (
          <p className="text-orange-400/60 text-xs mt-2">
            {lang === 'es' ? session.conditioning.scalingNote_es : session.conditioning.scalingNote}
          </p>
        )}
      </div>

      {/* Strategy */}
      <div className="border border-border rounded-lg p-4 bg-card">
        <h3 className="text-foreground font-bold mb-2 text-xs uppercase tracking-wider">
          {t('Strategy', 'Estrategia')}
        </h3>
        <p className="text-muted text-xs leading-relaxed">
          {lang === 'es' ? session.strategy_es : session.strategy}
        </p>
      </div>

      {/* Done Button */}
      {!readOnly && !done && !showLog && (
        <button
          onClick={() => setShowLog(true)}
          className="w-full px-4 py-4 bg-accent text-background font-bold rounded-lg hover:brightness-110 transition-all cursor-pointer text-lg done-button"
        >
          {t('Done', 'Hecho')}
        </button>
      )}

      {/* Exercise Log Panel */}
      {!readOnly && showLog && !done && (
        <ExerciseLogPanel
          date={session.date}
          strength={session.strength}
          onComplete={() => {
            markWorkoutDone(session.date, session.strength[0]?.exercise.level ?? 2, lang === 'es' ? session.sessionType_es : session.sessionType);
            setDone(true);
            setShowLog(false);
            onDone?.();
          }}
        />
      )}

      {/* Completed state */}
      {!readOnly && done && (
        <div className="w-full px-4 py-4 bg-accent/15 border-2 border-accent/30 text-accent font-bold rounded-lg text-center text-lg flex items-center justify-center gap-2">
          <svg className="w-6 h-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
            <polyline points="20 6 9 17 4 12" />
          </svg>
          {t('Completed', 'Completado')}
        </div>
      )}

      {/* Daily steps — BLUE */}
      <div className="flex items-center gap-3 rounded-lg border-2 border-blue-500/30 bg-blue-500/5 px-4 py-3">
        <svg className="w-5 h-5 text-blue-400 shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z" />
        </svg>
        <p className="text-blue-400 text-sm font-medium">
          {t('Walk 7,000-10,000 steps today. Non-negotiable.', 'Camina 7.000-10.000 pasos hoy. No negociable.')}
        </p>
      </div>

      {/* CTA nudge */}
      <div className="text-center border border-border rounded-lg p-4 bg-card">
        <p className="text-foreground text-sm font-medium">
          {t('Need to adapt this workout?', 'Necesitas adaptar este entreno?')}
        </p>
        <p className="text-muted text-xs mt-1">
          {t(
            'Injuries, limited equipment, or specific goals — copy the workout into ChatGPT and get a version tailored to you.',
            'Lesiones, equipamiento limitado, u objetivos concretos — copia el entreno en ChatGPT y consigue una version adaptada a ti.'
          )}
        </p>
      </div>

      {/* ChatGPT — Copy + Open (separate, like gist prompts) */}
      <div className="space-y-3">
        <div className="flex flex-col sm:flex-row gap-3">
          <button
            onClick={handleCopy}
            className="flex-1 px-6 py-3 bg-accent text-background font-semibold rounded-lg hover:brightness-110 transition-all cursor-pointer text-center"
          >
            {copied ? t('Copied!', 'Copiado!') : t('Copy Workout', 'Copiar Entreno')}
          </button>
          <a
            href="https://chatgpt.com/"
            target="_blank"
            rel="noopener noreferrer"
            className="flex-1 px-6 py-3 bg-card border border-accent text-accent font-semibold rounded-lg hover:bg-accent/10 transition-colors text-center"
          >
            {t('Open ChatGPT', 'Abrir ChatGPT')}
          </a>
        </div>
        <p className="text-muted text-xs text-center">
          {t(
            '1. Copy the workout  2. Open ChatGPT  3. Paste and customize',
            '1. Copia el entreno  2. Abre ChatGPT  3. Pega y personaliza'
          )}
        </p>
      </div>

      {/* Disclaimer */}
      <p className="text-muted/60 text-xs border-t border-border pt-4">
        {t(
          'This is not medical advice. If you experience sharp pain, dizziness, chest pain, or any symptom that concerns you — stop and consult a healthcare professional immediately.',
          'Esto no es consejo medico. Si experimentas dolor agudo, mareos, dolor en el pecho, o cualquier sintoma preocupante — para y consulta a un profesional de la salud inmediatamente.'
        )}
      </p>
    </div>
  );
}
